apiVersion: v1 
kind: Service 
metadata: 
  name: my-java-app-service 
spec: 
  selector: 
    app: my-java-app 
  ports: 
    - protocol: TCP 
      port: 80 # Service port (external/internal) 
      targetPort: 8080 # Container port 
  type: LoadBalancer # Use ClusterIP for internal only, NodePort for 
simple expose, LoadBalancer for cloud provider LB 